#!/bin/bash

# install google cloud sdk, instructions from https://cloud.google.com/sdk/docs/downloads-apt-get

export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
apt-get update && apt-get install -y google-cloud-sdk

echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
gcloud config set project $GCLOUD_PROJECT_ID
gcloud --quiet auth configure-docker
export GCLOUD_IMAGE_TAG="us.gcr.io/$GCLOUD_PROJECT_ID/ledge:$DOCKER_TAG"
docker tag $IMAGE_NAME $GCLOUD_IMAGE_TAG
docker push $GCLOUD_IMAGE_TAG

gcloud config set run/region us-central1
gcloud beta run deploy ledge --image $GCLOUD_IMAGE_TAG
