#!/bin/bash

# install google cloud sdk, instructions from https://cloud.google.com/sdk/docs/downloads-apt-get

export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
apt-get update && apt-get install -y google-cloud-sdk

echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
gcloud config set project $GCLOUD_PROJECT_ID
gcloud --quiet auth configure-docker
docker push us.gcr.io/$GCLOUD_PROJECT_ID]/ledge:latest
