// action types
export const RECEIVE_ACCOUNT = 'RECEIVE_ACCOUNT';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const CONFIRM_DELETE = 'CONFIRM_DELETE';
export const CANCEL_DELETE = 'CANCEL_DELETE';
export const RESET_FORM = 'RESET_FORM';
export const ALERT = 'ALERT';
export const DISMISS_ALERT = 'DISMISS_ALERT';
export const LOAD_MORE = 'LOAD_MORE';
